/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.alocadorSalas.view;

import br.uff.alocadorSalas.controller.CursosController;
import br.uff.alocadorSalas.controller.ProfessorController;
import br.uff.alocadorSalas.model.Curso;
import br.uff.alocadorSalas.model.Professor;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Evandro
 */
public class JPanelProfessores extends javax.swing.JPanel {

    EstadoTela estadoTela;
    Long idProfessorCorrente;

    public JPanelProfessores() {
        initComponents();

        idProfessorCorrente = (long) 0;

        configInicial();
        definirLayout(EstadoTela.inicial);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelConfiguracaoProfessores = new javax.swing.JPanel();
        lNomeProfessores = new javax.swing.JLabel();
        JTextNome = new javax.swing.JTextField();
        panelBotoesAcao = new javax.swing.JPanel();
        JButtonExcluir = new javax.swing.JButton();
        JButtonAlterar = new javax.swing.JButton();
        JButtonBuscar = new javax.swing.JButton();
        JButtonCadastrar = new javax.swing.JButton();
        painelPesquisaCursos4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablePesquisa = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));

        painelConfiguracaoProfessores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Professores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 102, 102))); // NOI18N

        lNomeProfessores.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lNomeProfessores.setText("Nome.:");

        javax.swing.GroupLayout painelConfiguracaoProfessoresLayout = new javax.swing.GroupLayout(painelConfiguracaoProfessores);
        painelConfiguracaoProfessores.setLayout(painelConfiguracaoProfessoresLayout);
        painelConfiguracaoProfessoresLayout.setHorizontalGroup(
            painelConfiguracaoProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracaoProfessoresLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lNomeProfessores)
                .addGap(18, 18, 18)
                .addComponent(JTextNome, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelConfiguracaoProfessoresLayout.setVerticalGroup(
            painelConfiguracaoProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracaoProfessoresLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(painelConfiguracaoProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomeProfessores)
                    .addComponent(JTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        panelBotoesAcao.setMaximumSize(new java.awt.Dimension(700, 75));
        panelBotoesAcao.setMinimumSize(new java.awt.Dimension(700, 75));

        JButtonExcluir.setText("Excluir");
        JButtonExcluir.setMaximumSize(new java.awt.Dimension(150, 50));
        JButtonExcluir.setMinimumSize(new java.awt.Dimension(150, 50));
        JButtonExcluir.setName("JButtonExcluir"); // NOI18N
        JButtonExcluir.setPreferredSize(new java.awt.Dimension(150, 50));
        JButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonExcluirActionPerformed(evt);
            }
        });

        JButtonAlterar.setText("Alterar");
        JButtonAlterar.setMaximumSize(new java.awt.Dimension(150, 50));
        JButtonAlterar.setMinimumSize(new java.awt.Dimension(150, 50));
        JButtonAlterar.setName("JButtonAlterar"); // NOI18N
        JButtonAlterar.setPreferredSize(new java.awt.Dimension(150, 50));
        JButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesAcaoLayout = new javax.swing.GroupLayout(panelBotoesAcao);
        panelBotoesAcao.setLayout(panelBotoesAcaoLayout);
        panelBotoesAcaoLayout.setHorizontalGroup(
            panelBotoesAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotoesAcaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        panelBotoesAcaoLayout.setVerticalGroup(
            panelBotoesAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesAcaoLayout.createSequentialGroup()
                .addGroup(panelBotoesAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JButtonBuscar.setText("Buscar");
        JButtonBuscar.setMaximumSize(new java.awt.Dimension(150, 50));
        JButtonBuscar.setMinimumSize(new java.awt.Dimension(150, 50));
        JButtonBuscar.setName("JButtonBuscar"); // NOI18N
        JButtonBuscar.setPreferredSize(new java.awt.Dimension(150, 50));
        JButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonBuscarActionPerformed(evt);
            }
        });

        JButtonCadastrar.setText("Cadastrar");
        JButtonCadastrar.setMaximumSize(new java.awt.Dimension(150, 50));
        JButtonCadastrar.setMinimumSize(new java.awt.Dimension(150, 50));
        JButtonCadastrar.setName("JButtonCadastrar"); // NOI18N
        JButtonCadastrar.setPreferredSize(new java.awt.Dimension(150, 50));
        JButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCadastrarActionPerformed(evt);
            }
        });

        painelPesquisaCursos4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Resultado da Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 100));

        JTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTablePesquisa.setShowHorizontalLines(false);
        JTablePesquisa.setShowVerticalLines(false);
        jScrollPane1.setViewportView(JTablePesquisa);

        javax.swing.GroupLayout painelPesquisaCursos4Layout = new javax.swing.GroupLayout(painelPesquisaCursos4);
        painelPesquisaCursos4.setLayout(painelPesquisaCursos4Layout);
        painelPesquisaCursos4Layout.setHorizontalGroup(
            painelPesquisaCursos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaCursos4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelPesquisaCursos4Layout.setVerticalGroup(
            painelPesquisaCursos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaCursos4Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelConfiguracaoProfessores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelBotoesAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 680, Short.MAX_VALUE)
                    .addComponent(painelPesquisaCursos4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelConfiguracaoProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelPesquisaCursos4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBotoesAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonExcluirActionPerformed
        if (JTablePesquisa.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhum professor selecionado");
            return;
        }

        try {
            DefaultTableModel modelTable = (DefaultTableModel) JTablePesquisa.getModel();

            String nomeProfessorSelecionado = String.valueOf(modelTable.getValueAt(JTablePesquisa.getSelectedRow(), 0));
            Professor professorSelecionado = (Professor) new ProfessorController().buscaProfessorPorNome(nomeProfessorSelecionado);

            new ProfessorController().excluir(professorSelecionado.getId());
            modelTable.removeRow(JTablePesquisa.getSelectedRow());

            JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Problemas ao excluir o professor!");
        }
    }//GEN-LAST:event_JButtonExcluirActionPerformed

    private void JButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAlterarActionPerformed
        try {
            if (JTablePesquisa.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Nenhum curso selecionado!");
                return;
            }

            DefaultTableModel modelTable = (DefaultTableModel) JTablePesquisa.getModel();
            String nomeProfessorSelecionado = String.valueOf(modelTable.getValueAt(JTablePesquisa.getSelectedRow(), 0));
            Professor professorSelecionado = (Professor) new ProfessorController().buscaProfessorPorNome(nomeProfessorSelecionado);

            this.JTextNome.setText(professorSelecionado.getNome());
            this.idProfessorCorrente = professorSelecionado.getId();
            modelTable.removeRow(JTablePesquisa.getSelectedRow());

            definirLayout(EstadoTela.alterando);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Problemas na alteração!");
        }
    }//GEN-LAST:event_JButtonAlterarActionPerformed

    private void JButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonBuscarActionPerformed
        ArrayList<Professor> professoresBuscados = new ArrayList<>();

        if (JTextNome.getText().equalsIgnoreCase("")) {
            try {
                professoresBuscados = new ArrayList<>(new ProfessorController().listaProfessor());
            } catch (Exception e) {
                return;
            }
        } else if (!JTextNome.getText().equalsIgnoreCase("")) {
            try {
                professoresBuscados = new ArrayList<>(new ProfessorController().buscaTodosProfessorPorNome(JTextNome.getText()));
            } catch (Exception e) {
                return;
            }
        }

        if (professoresBuscados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum professor encontrado!");
            return;
        }

        DefaultTableModel modelTable = (DefaultTableModel) JTablePesquisa.getModel();
        modelTable.setRowCount(0);
        for (Professor p : professoresBuscados) {
            modelTable.addRow(new Object[]{p});
        }

        definirLayout(EstadoTela.inicial);
    }//GEN-LAST:event_JButtonBuscarActionPerformed

    private void JButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCadastrarActionPerformed
        if ((JTextNome.getText().equalsIgnoreCase(""))) {
            JOptionPane.showMessageDialog(this, "Campo de busca 'Nome' vazio!");
            return;
        }

        if (JButtonCadastrar.getText().equalsIgnoreCase("Cadastrar")) {
            try {
                new ProfessorController().salvar(JTextNome.getText());
                JOptionPane.showMessageDialog(this, "Cadastrado com sucesso!");
            } catch (Exception ex) {
                Logger.getLogger(JPanelCursos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (JButtonCadastrar.getText().equalsIgnoreCase("Alterar")) {

            if (idProfessorCorrente == 0) {
                JOptionPane.showMessageDialog(this, "Nenhum professor para ser alterado!");
                return;
            }

            try {
                new ProfessorController().alterar(idProfessorCorrente, JTextNome.getText());
                JOptionPane.showMessageDialog(this, "Alterado com sucesso!");
            } catch (Exception ex) {
                Logger.getLogger(JPanelCursos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        definirLayout(EstadoTela.inicial);
    }//GEN-LAST:event_JButtonCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAlterar;
    private javax.swing.JButton JButtonBuscar;
    private javax.swing.JButton JButtonCadastrar;
    private javax.swing.JButton JButtonExcluir;
    private javax.swing.JTable JTablePesquisa;
    private javax.swing.JTextField JTextNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lNomeProfessores;
    private javax.swing.JPanel painelConfiguracaoProfessores;
    private javax.swing.JPanel painelPesquisaCursos4;
    private javax.swing.JPanel panelBotoesAcao;
    // End of variables declaration//GEN-END:variables

    private void configInicial() {
        Color c = new Color(this.getBackground().getRGB());

        this.JButtonAlterar.setBackground(c);
        this.JButtonBuscar.setBackground(c);
        this.JButtonCadastrar.setBackground(c);
        this.JButtonExcluir.setBackground(c);
    }

    private void definirLayout(EstadoTela estado) {

        estadoTela = estado;

        if (estadoTela.equals(EstadoTela.inicial)) {
            JButtonExcluir.setEnabled(true);
            JButtonAlterar.setEnabled(true);
            JButtonBuscar.setEnabled(true);
            JButtonCadastrar.setEnabled(true);

            JButtonCadastrar.setText("Cadastrar");

            this.JTextNome.setText("");
        }

        if (estadoTela.equals(EstadoTela.alterando)) {
            JButtonExcluir.setEnabled(false);
            JButtonAlterar.setEnabled(false);
            JButtonBuscar.setEnabled(false);
            JButtonCadastrar.setEnabled(true);

            JButtonCadastrar.setText("Alterar");
        }
    }

}
