/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.alocadorSalas.view;

/**
 *
 * @author Evandro
 */
public class JPanelGlobal extends javax.swing.JPanel {

    /**
     * Creates new form JPanelGlobal
     */
    public JPanelGlobal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelMenu = new br.uff.alocadorSalas.view.JPanelMenu();
        JPanelTela = new javax.swing.JPanel();

        JPanelTela.setMaximumSize(new java.awt.Dimension(700, 600));
        JPanelTela.setMinimumSize(new java.awt.Dimension(700, 600));

        javax.swing.GroupLayout JPanelTelaLayout = new javax.swing.GroupLayout(JPanelTela);
        JPanelTela.setLayout(JPanelTelaLayout);
        JPanelTelaLayout.setHorizontalGroup(
            JPanelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        JPanelTelaLayout.setVerticalGroup(
            JPanelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JPanelTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPanelTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.uff.alocadorSalas.view.JPanelMenu JPanelMenu;
    private javax.swing.JPanel JPanelTela;
    // End of variables declaration//GEN-END:variables

    public void alteraVisibilidade(String nomeBotao) {

        if (nomeBotao.equalsIgnoreCase("JButtonCursos")) {

            JPanelCursos panelCursos = new JPanelCursos();
            panelCursos.setVisible(true);

            JPanelTela.setVisible(true);
            JPanelTela.setLayout(new java.awt.BorderLayout());
            JPanelTela.removeAll();
            JPanelTela.add(panelCursos);
            JPanelTela.revalidate();

        }

        if (nomeBotao.equalsIgnoreCase("JButtonInicial")) {

            JPanelInicial panelInicial = new JPanelInicial();
            panelInicial.setVisible(true);
            
            JPanelTela.setVisible(true);
            JPanelTela.setLayout(new java.awt.BorderLayout());
            JPanelTela.removeAll();
            JPanelTela.revalidate();
            JPanelTela.repaint();

        }

        if (nomeBotao.equalsIgnoreCase("JButtonDisciplinas")) {

            JPanelDisciplinas panelDisciplinas = new JPanelDisciplinas();
            panelDisciplinas.setVisible(true);

            JPanelTela.setVisible(true);
            JPanelTela.setLayout(new java.awt.BorderLayout());
            JPanelTela.removeAll();
            JPanelTela.add(panelDisciplinas);
            JPanelTela.revalidate();

        }

        if (nomeBotao.equalsIgnoreCase("JButtonSalas")) {

            JPanelSalas panelSalas = new JPanelSalas();
            panelSalas.setVisible(true);

            JPanelTela.setVisible(true);
            JPanelTela.setLayout(new java.awt.BorderLayout());
            JPanelTela.removeAll();
            JPanelTela.add(panelSalas);
            JPanelTela.revalidate();

        }

        if (nomeBotao.equalsIgnoreCase("JButtonTurmas")) {

            JPanelTurmas panelTurmas = new JPanelTurmas();
            panelTurmas.setVisible(true);

            JPanelTela.setVisible(true);
            JPanelTela.setLayout(new java.awt.BorderLayout());
            JPanelTela.removeAll();
            JPanelTela.add(panelTurmas);
            JPanelTela.revalidate();

        }
        
        if (nomeBotao.equalsIgnoreCase("JButtonProfessores")) {
            
            JPanelProfessores panelProfessores = new JPanelProfessores();
            panelProfessores.setVisible(true);
           
            JPanelTela.setVisible(true); 
            JPanelTela.setLayout(new java.awt.BorderLayout());  
            JPanelTela.removeAll();
            JPanelTela.add(panelProfessores); 
            JPanelTela.revalidate();                       
            
        }
        //painelInicial.setVisible(nomeBotao.equalsIgnoreCase("botaoInicio"));
        //painelCursos.setVisible(nomeBotao.equalsIgnoreCase("botaoCursos"));
        //painelProfessores.setVisible(nomeBotao.equalsIgnoreCase("botaoProfessores"));
        //painelDisciplinas.setVisible(nomeBotao.equalsIgnoreCase("botaoDisciplinas"));
        //painelHorarios.setVisible(nomeBotao.equalsIgnoreCase("botaoHorarios"));
        //painelSalas.setVisible(nomeBotao.equalsIgnoreCase("botaoSalas"));
        //painelGrade.setVisible(nomeBotao.equalsIgnoreCase("botaoGrade"));

    }

    public void alteraCorBotao(String nomeBotao) {
        //botaoCursos.setBackground(nomeBotao.equalsIgnoreCase("botaoCursos") ? Color.ORANGE : new Color(240, 240, 240));
        //botaoHorarios.setBackground(nomeBotao.equalsIgnoreCase("botaoHorarios") ? Color.ORANGE : new Color(240, 240, 240));
        //botaoSalas.setBackground(nomeBotao.equalsIgnoreCase("botaoSalas") ? Color.ORANGE : new Color(240, 240, 240));
        //botaoProfessores.setBackground(nomeBotao.equalsIgnoreCase("botaoProfessores") ? Color.ORANGE : new Color(240, 240, 240));
        //botaoDisciplinas.setBackground(nomeBotao.equalsIgnoreCase("botaoDisciplinas") ? Color.ORANGE : new Color(240, 240, 240));
        //setBackground(nomeBotao.equalsIgnoreCase("botaoInicio") ? Color.ORANGE : new Color(240, 240, 240));
        //botaoGrade.setBackground(nomeBotao.equalsIgnoreCase("botaoGrade") ? Color.ORANGE : new Color(240, 240, 240));
    }

}
