/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.alocadorSalas.view;

import br.uff.alocadorSalas.controller.AulaController;
import br.uff.alocadorSalas.controller.CursosController;
import br.uff.alocadorSalas.controller.DisciplinaController;
import br.uff.alocadorSalas.controller.HorarioController;
import br.uff.alocadorSalas.controller.ProfessorController;
import br.uff.alocadorSalas.controller.SalaController;
import br.uff.alocadorSalas.controller.TurmaController;
import br.uff.alocadorSalas.model.Aula;
import br.uff.alocadorSalas.model.Curso;
import br.uff.alocadorSalas.model.Disciplina;
import br.uff.alocadorSalas.model.Horario;
import br.uff.alocadorSalas.model.Professor;
import br.uff.alocadorSalas.model.Sala;
import br.uff.alocadorSalas.model.Turma;
import java.awt.Color;
import java.sql.Time;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Evandro
 */
public class JPanelTurmas extends javax.swing.JPanel {

    /**
     * Variáveis
     */
    EstadoTela estadoTela;
    Long idTurmaCorrente;
    List<Aula> listaAulasCorrente;

    /**
     * Creates new form JPanelTurmas
     */
    public JPanelTurmas() {
        initComponents();

        idTurmaCorrente = (long) 0;

        configInicial();
        preencherComboCurso();
        preencherComboProfessores();
        preencherComboDiaSemana();
        preencherComboSalas();
        definirLayout(EstadoTela.inicial);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTextNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JSpinnerQuantidadeAlunos = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JComboBoxCurso = new javax.swing.JComboBox();
        JComboBoxProfessor = new javax.swing.JComboBox();
        JComboBoxDisciplina = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JComboBoxSala = new javax.swing.JComboBox();
        JComboBoxDiaSemana = new javax.swing.JComboBox();
        JButtonIncluiAula = new javax.swing.JButton();
        JButtonRemoveAula = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTableAulas = new javax.swing.JTable();
        JFormattedTextHorarioInicial = new javax.swing.JFormattedTextField();
        JFormattedTextHorarioFinal = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        JButtonBuscar = new javax.swing.JButton();
        JButtonCadastrar = new javax.swing.JButton();
        painelPesquisaCursos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablePesquisa = new javax.swing.JTable();
        JButtonExcluir = new javax.swing.JButton();
        JButtonAlterar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Turmas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Nome.:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Quantidade de alunos.:");

        JSpinnerQuantidadeAlunos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));
        JSpinnerQuantidadeAlunos.setName("JSpinnerQuantidadeAlunos"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Disciplina.:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Professor.:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Curso.:");

        JComboBoxCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboBoxCursoItemStateChanged(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar Horários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("<html><font color=black>Sala</font> <font color=red>*</font></html>");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Dia da Semana.:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Horário Inicial.:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Horário Final.:");

        JButtonIncluiAula.setText("->");
        JButtonIncluiAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonIncluiAulaActionPerformed(evt);
            }
        });

        JButtonRemoveAula.setText("<-");
        JButtonRemoveAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonRemoveAulaActionPerformed(evt);
            }
        });

        jScrollPane3.setPreferredSize(new java.awt.Dimension(50, 50));

        JTableAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Horário Inicial", "Horário Final", "Dia Semana", "Sala"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableAulas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JTableAulas.setShowHorizontalLines(false);
        JTableAulas.setShowVerticalLines(false);
        jScrollPane3.setViewportView(JTableAulas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JFormattedTextHorarioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JComboBoxSala, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JComboBoxDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JFormattedTextHorarioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButtonIncluiAula)
                    .addComponent(JButtonRemoveAula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JButtonIncluiAula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JButtonRemoveAula))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(JComboBoxSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(JComboBoxDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(JFormattedTextHorarioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(JFormattedTextHorarioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTextNome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JSpinnerQuantidadeAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JComboBoxCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JComboBoxProfessor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JComboBoxDisciplina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JSpinnerQuantidadeAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JComboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JComboBoxDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JComboBoxProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("* Campo opcional");

        JButtonBuscar.setText("Buscar");
        JButtonBuscar.setMaximumSize(new java.awt.Dimension(150, 50));
        JButtonBuscar.setMinimumSize(new java.awt.Dimension(150, 50));
        JButtonBuscar.setName("JButtonBuscar"); // NOI18N
        JButtonBuscar.setPreferredSize(new java.awt.Dimension(150, 50));
        JButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonBuscarActionPerformed(evt);
            }
        });

        JButtonCadastrar.setText("Cadastrar");
        JButtonCadastrar.setMaximumSize(new java.awt.Dimension(150, 50));
        JButtonCadastrar.setMinimumSize(new java.awt.Dimension(150, 50));
        JButtonCadastrar.setName("JButtonCadastrar"); // NOI18N
        JButtonCadastrar.setPreferredSize(new java.awt.Dimension(150, 50));
        JButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCadastrarActionPerformed(evt);
            }
        });

        painelPesquisaCursos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Resultado da Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 100));

        JTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Quantidade de alunos", "Curso", "Disciplina", "Professor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTablePesquisa.setShowHorizontalLines(false);
        JTablePesquisa.setShowVerticalLines(false);
        jScrollPane1.setViewportView(JTablePesquisa);

        javax.swing.GroupLayout painelPesquisaCursosLayout = new javax.swing.GroupLayout(painelPesquisaCursos);
        painelPesquisaCursos.setLayout(painelPesquisaCursosLayout);
        painelPesquisaCursosLayout.setHorizontalGroup(
            painelPesquisaCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );
        painelPesquisaCursosLayout.setVerticalGroup(
            painelPesquisaCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        );

        JButtonExcluir.setText("Excluir");
        JButtonExcluir.setMaximumSize(new java.awt.Dimension(150, 50));
        JButtonExcluir.setMinimumSize(new java.awt.Dimension(150, 50));
        JButtonExcluir.setName("JButtonExcluir"); // NOI18N
        JButtonExcluir.setPreferredSize(new java.awt.Dimension(150, 50));
        JButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonExcluirActionPerformed(evt);
            }
        });

        JButtonAlterar.setText("Alterar");
        JButtonAlterar.setMaximumSize(new java.awt.Dimension(150, 50));
        JButtonAlterar.setMinimumSize(new java.awt.Dimension(150, 50));
        JButtonAlterar.setName("JButtonAlterar"); // NOI18N
        JButtonAlterar.setPreferredSize(new java.awt.Dimension(150, 50));
        JButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelPesquisaCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPesquisaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JButtonAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCadastrarActionPerformed
        DefaultTableModel modelTableHorarios = (DefaultTableModel) JTableAulas.getModel();
        DefaultComboBoxModel modelDisciplinas = (DefaultComboBoxModel) JComboBoxDisciplina.getModel();
        DefaultComboBoxModel modelCursos = (DefaultComboBoxModel) JComboBoxCurso.getModel();
        DefaultComboBoxModel modelProfessores = (DefaultComboBoxModel) JComboBoxProfessor.getModel();

        if ((JTextNome.getText().equalsIgnoreCase(""))
                || (JComboBoxCurso.getSelectedIndex() <= 0)
                || (JComboBoxDisciplina.getSelectedIndex() <= 0)
                || (JComboBoxProfessor.getSelectedIndex() <= 0)
                || ((int) JSpinnerQuantidadeAlunos.getValue() < 1)
                || (modelTableHorarios.getRowCount() <= 0)) {
            JOptionPane.showMessageDialog(this, "Algum campo vazio!");
            return;
        }

        if (JButtonCadastrar.getText().equalsIgnoreCase("Cadastrar")) {
            try {
                new TurmaController().salvar(JTextNome.getText(),
                        (int) JSpinnerQuantidadeAlunos.getValue(),
                        (Disciplina) modelDisciplinas.getSelectedItem(),
                        (Professor) modelProfessores.getSelectedItem(),
                        (Curso) modelCursos.getSelectedItem());

                Turma turma = new TurmaController().buscaTurmaPorNomeEDisciplina(JTextNome.getText(), (Disciplina) modelDisciplinas.getSelectedItem());

                for (int i = 0; i < modelTableHorarios.getRowCount(); i++) {
                    Horario h = new Horario();
                    h.setHorarioInicial((long) modelTableHorarios.getValueAt(JTableAulas.getSelectedRow(), 0));
                    h.setHorarioFinal((long) modelTableHorarios.getValueAt(JTableAulas.getSelectedRow(), 1));
                    new HorarioController().salvar(h.getHorarioInicial(), h.getHorarioFinal());

                    Aula a = new Aula();
                    a.setTurma(turma);
                    a.setHorario(h);
                    a.setDiaSemana(String.valueOf(modelTableHorarios.getValueAt(JTableAulas.getSelectedRow(), 2)));
                    if (!String.valueOf(modelTableHorarios.getValueAt(JTableAulas.getSelectedRow(), 3)).isEmpty()) {
                        a.setSala(new SalaController().buscaSalaPorNome(String.valueOf(modelTableHorarios.getValueAt(JTableAulas.getSelectedRow(), 3))));
                    }
                    new AulaController().salvar(a.getDiaSemana(), a.getTurma(), a.getSala(), a.getHorario());
                }

                JOptionPane.showMessageDialog(this, "Cadastrado com sucesso!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Problemas no cadastro!");
            }
        }

        if (JButtonCadastrar.getText().equalsIgnoreCase("Alterar")) {
            if (idTurmaCorrente == 0) {
                JOptionPane.showMessageDialog(this, "Nenhuma turma para ser alterado!");
                return;
            }
            try {
                new TurmaController().alterar(
                        idTurmaCorrente,
                        JTextNome.getText(),
                        (int) JSpinnerQuantidadeAlunos.getValue(),
                        (Disciplina) modelDisciplinas.getSelectedItem(),
                        (Professor) modelProfessores.getSelectedItem(),
                        (Curso) modelCursos.getSelectedItem());

                for (int i = 0; i < modelTableHorarios.getRowCount(); i++) {

                    Horario h = new HorarioController().buscarPorHorarioInicialEFinal(
                            (long) modelTableHorarios.getValueAt(JTableAulas.getSelectedRow(), 0),
                            (long) modelTableHorarios.getValueAt(JTableAulas.getSelectedRow(), 1));

                    if (h == null) {
                        new HorarioController().salvar(
                                (long) modelTableHorarios.getValueAt(JTableAulas.getSelectedRow(), 0),
                                (long) modelTableHorarios.getValueAt(JTableAulas.getSelectedRow(), 1));
                    } else {
                        new HorarioController().alterar(h.getId(), h.getHorarioInicial(), h.getHorarioFinal());
                    }

                    Aula a = new AulaController().buscarPorSalaHorarioeDiaSemana(
                            (Sala) modelTableHorarios.getValueAt(JTableAulas.getSelectedRow(), 3),
                            h,
                            String.valueOf(modelTableHorarios.getValueAt(JTableAulas.getSelectedRow(), 2)));

                }

                JOptionPane.showMessageDialog(this, "Alterado com sucesso!");
                idTurmaCorrente = Long.valueOf(0);
            } catch (Exception ex) {
                Logger.getLogger(JPanelSalas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        definirLayout(EstadoTela.inicial);
    }//GEN-LAST:event_JButtonCadastrarActionPerformed

    private void JButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonExcluirActionPerformed
        if (JTablePesquisa.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhuma turma selecionada");
            return;
        }

        try {
            DefaultTableModel model = (DefaultTableModel) JTablePesquisa.getModel();

            String nomeTurmaSelecionado = (String) model.getValueAt(JTablePesquisa.getSelectedRow(), 0);
            String nomeDisciplinaSelecionado = (String) model.getValueAt(JTablePesquisa.getSelectedRow(), 3);

            Disciplina disciplinaSelecionada = new DisciplinaController().buscaDisciplinaPorNome(nomeDisciplinaSelecionado);

            Turma turma = new TurmaController().buscaTurmaPorNomeEDisciplina(nomeTurmaSelecionado, disciplinaSelecionada);

            new TurmaController().excluir(turma.getId());
            model.removeRow(JTablePesquisa.getSelectedRow());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Problemas ao excluir turma!");
        }
    }//GEN-LAST:event_JButtonExcluirActionPerformed

    private void JButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAlterarActionPerformed

        if (JTablePesquisa.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhuma turma selecionada");
            return;
        }

        try {
            DefaultTableModel modelTable = (DefaultTableModel) JTablePesquisa.getModel();
            Turma turma = (Turma) modelTable.getValueAt(JTablePesquisa.getSelectedRow(), 0);

            this.JTextNome.setText(turma.getNome());
            this.JSpinnerQuantidadeAlunos.setValue(turma.getQuantidadeAlunos());
            this.JComboBoxCurso.setSelectedItem(turma.getCurso());
            this.JComboBoxDisciplina.setSelectedItem(turma.getDisciplina());
            this.JComboBoxProfessor.setSelectedItem(turma.getProfessor());

            DefaultTableModel modelAulas = (DefaultTableModel) JTableAulas.getModel();
            modelAulas.setRowCount(0);

            List<Aula> aulas = new AulaController().buscaTodosPorTurma(turma);
            for (Aula a : aulas) {
                modelAulas.addRow(new Object[]{a.getHorario().getHorarioInicial(), a.getHorario().getHorarioFinal(), a.getDiaSemana(), a.getSala()});
            }

            listaAulasCorrente = aulas;
            idTurmaCorrente = turma.getId();
            modelTable.removeRow(JTablePesquisa.getSelectedRow());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Problema ao alterar turma!");
        }

        definirLayout(EstadoTela.alterando);
    }//GEN-LAST:event_JButtonAlterarActionPerformed

    private void JButtonIncluiAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonIncluiAulaActionPerformed
        DefaultComboBoxModel modelDiaSemana = (DefaultComboBoxModel) JComboBoxDiaSemana.getModel();
        DefaultComboBoxModel modelSala = (DefaultComboBoxModel) JComboBoxSala.getModel();

        Horario horario = new Horario();
        horario.setHorarioInicial(Time.valueOf(JFormattedTextHorarioInicial.getText()).getTime());
        horario.setHorarioFinal(Time.valueOf(JFormattedTextHorarioFinal.getText()).getTime());

        Aula aula = new Aula();
        aula.setHorario(horario);
        aula.setDiaSemana(modelDiaSemana.getSelectedItem().toString());
        if (JComboBoxSala.getSelectedIndex() > 0) {
            aula.setSala((Sala) modelSala.getSelectedItem());
        }        
        
        DefaultTableModel modelAulas = (DefaultTableModel) JTableAulas.getModel();
        modelAulas.addRow(new Object[]{new Time(aula.getHorario().getHorarioInicial()).toString(), new Time(aula.getHorario().getHorarioFinal()).toString(), aula.getDiaSemana(), aula.getSala()});
    }//GEN-LAST:event_JButtonIncluiAulaActionPerformed

    private void JButtonRemoveAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonRemoveAulaActionPerformed
        DefaultComboBoxModel modelDiaSemana = (DefaultComboBoxModel) JComboBoxDiaSemana.getModel();
        DefaultComboBoxModel modelSala = (DefaultComboBoxModel) JComboBoxSala.getModel();
        DefaultTableModel modelAulas = (DefaultTableModel) JTableAulas.getModel();

        Horario horario = new Horario();
        horario.setHorarioInicial(Time.valueOf(modelAulas.getValueAt(JTableAulas.getSelectedRow(), 0).toString()).getTime());
        horario.setHorarioFinal(Time.valueOf(modelAulas.getValueAt(JTableAulas.getSelectedRow(), 1).toString()).getTime());

        Aula aula = new Aula();
        aula.setHorario(horario);
        aula.setDiaSemana(modelAulas.getValueAt(JTableAulas.getSelectedRow(), 2).toString());
        aula.setSala((Sala) modelAulas.getValueAt(JTableAulas.getSelectedRow(), 3));

        modelDiaSemana.setSelectedItem(aula.getDiaSemana());
        JFormattedTextHorarioInicial.setText(aula.getHorario().getHorarioInicial().toString());
        JFormattedTextHorarioFinal.setText(aula.getHorario().getHorarioFinal().toString());
        if (aula.getSala() != null) {
            modelSala.setSelectedItem(aula.getSala());
        }

        modelAulas.removeRow(JTableAulas.getSelectedRow());
    }//GEN-LAST:event_JButtonRemoveAulaActionPerformed

    private void JComboBoxCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboBoxCursoItemStateChanged
        DefaultComboBoxModel modelCurso = (DefaultComboBoxModel) JComboBoxCurso.getModel();

        if (JComboBoxCurso.getSelectedIndex() > 0) {
            preencherComboDisciplina((Curso) modelCurso.getSelectedItem());
        } else {
            preencherComboDisciplina(new Curso());
        }
    }//GEN-LAST:event_JComboBoxCursoItemStateChanged

    private void JButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonBuscarActionPerformed

        DefaultTableModel modelAulas = (DefaultTableModel) JTableAulas.getModel();
        DefaultComboBoxModel modelDisciplinas = (DefaultComboBoxModel) JComboBoxDisciplina.getModel();
        DefaultComboBoxModel modelCursos = (DefaultComboBoxModel) JComboBoxCurso.getModel();
        DefaultComboBoxModel modelProfessores = (DefaultComboBoxModel) JComboBoxProfessor.getModel();
        ArrayList<Turma> turmasBuscadas = new ArrayList<>();

        try {
            if ((JTextNome.getText().equalsIgnoreCase(""))
                    && (JComboBoxCurso.getSelectedIndex() <= 0)
                    && (JComboBoxDisciplina.getSelectedIndex() <= 0)
                    && (JComboBoxProfessor.getSelectedIndex() <= 0)
                    && (modelAulas.getRowCount() <= 0)) {

                turmasBuscadas = new ArrayList<>(new TurmaController().listaTurmas());

            } else if (!JTextNome.getText().equalsIgnoreCase("") && (JComboBoxDisciplina.getSelectedIndex() >= 0)) {

                turmasBuscadas = new ArrayList<>(new TurmaController().buscaTodasTurmaPorNomeEDisciplina(JTextNome.getText(), (Disciplina) modelDisciplinas.getElementAt(JComboBoxDisciplina.getSelectedIndex())));

            } else if (!JTextNome.getText().equalsIgnoreCase("")) {

                turmasBuscadas = new ArrayList<>(new TurmaController().buscaTodasTurmaPorNome(JTextNome.getText()));

            } else if (JComboBoxCurso.getSelectedIndex() >= 0) {

                turmasBuscadas = new ArrayList<>(new TurmaController().buscaTodasPorCurso((Curso) modelCursos.getElementAt(JComboBoxCurso.getSelectedIndex())));

            } else if (JComboBoxDisciplina.getSelectedIndex() >= 0) {

                turmasBuscadas = new ArrayList<>(new TurmaController().buscaTodasPorDisciplina((Disciplina) modelDisciplinas.getElementAt(JComboBoxDisciplina.getSelectedIndex())));

            } else if (JComboBoxProfessor.getSelectedIndex() >= 0) {

                turmasBuscadas = new ArrayList<>(new TurmaController().buscaTodasPorProfessor((Professor) modelProfessores.getElementAt(JComboBoxProfessor.getSelectedIndex())));

            }
        } catch (Exception ex) {
            Logger.getLogger(JPanelTurmas.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        if (turmasBuscadas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhuma turma encontrada!");
            return;
        }

        DefaultTableModel modelTable = (DefaultTableModel) JTablePesquisa.getModel();
        modelTable.setRowCount(0);

        for (Turma t : turmasBuscadas) {
            modelTable.addRow(new Object[]{t.getNome(), t.getQuantidadeAlunos(), t.getCurso(), t.getDisciplina(), t.getProfessor()});
        }        

        definirLayout(EstadoTela.inicial);
    }//GEN-LAST:event_JButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAlterar;
    private javax.swing.JButton JButtonBuscar;
    private javax.swing.JButton JButtonCadastrar;
    private javax.swing.JButton JButtonExcluir;
    private javax.swing.JButton JButtonIncluiAula;
    private javax.swing.JButton JButtonRemoveAula;
    private javax.swing.JComboBox JComboBoxCurso;
    private javax.swing.JComboBox JComboBoxDiaSemana;
    private javax.swing.JComboBox JComboBoxDisciplina;
    private javax.swing.JComboBox JComboBoxProfessor;
    private javax.swing.JComboBox JComboBoxSala;
    private javax.swing.JFormattedTextField JFormattedTextHorarioFinal;
    private javax.swing.JFormattedTextField JFormattedTextHorarioInicial;
    private javax.swing.JSpinner JSpinnerQuantidadeAlunos;
    private javax.swing.JTable JTableAulas;
    private javax.swing.JTable JTablePesquisa;
    private javax.swing.JTextField JTextNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel painelPesquisaCursos;
    // End of variables declaration//GEN-END:variables

    private void configInicial() {
        Color c = new Color(this.getBackground().getRGB());

        this.JButtonAlterar.setBackground(c);
        this.JButtonBuscar.setBackground(c);
        this.JButtonCadastrar.setBackground(c);
        this.JButtonExcluir.setBackground(c);
    }

    private void definirLayout(EstadoTela estado) {
        estadoTela = estado;

        if (estadoTela.equals(EstadoTela.inicial)) {
            JButtonExcluir.setEnabled(true);
            JButtonAlterar.setEnabled(true);
            JButtonBuscar.setEnabled(true);
            JButtonCadastrar.setEnabled(true);

            JButtonCadastrar.setText("Cadastrar");

            this.JTextNome.setText("");
            this.JComboBoxCurso.setSelectedIndex(0);
            this.JComboBoxDisciplina.setSelectedIndex(0);
            this.JComboBoxSala.setSelectedIndex(0);
            this.JComboBoxProfessor.setSelectedIndex(0);
            this.JComboBoxDiaSemana.setSelectedIndex(0);
        }

        if (estadoTela.equals(EstadoTela.alterando)) {
            JButtonExcluir.setEnabled(false);
            JButtonAlterar.setEnabled(false);
            JButtonBuscar.setEnabled(false);
            JButtonCadastrar.setEnabled(true);

            JButtonCadastrar.setText("Alterar");
        }
    }

    private void preencherComboCurso() {
        DefaultComboBoxModel modelCurso = (DefaultComboBoxModel) JComboBoxCurso.getModel();
        modelCurso.removeAllElements();

        String mensagem = "Preencha com um curso!";
        modelCurso.addElement(mensagem);

        try {
            ArrayList<Curso> cursosBuscados = new ArrayList<>(new CursosController().listaCursos());
            for (Curso c : cursosBuscados) {
                modelCurso.addElement(c);

            }
        } catch (Exception ex) {
            Logger.getLogger(JPanelDisciplinas.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

        modelCurso.setSelectedItem(mensagem);
    }

    private void preencherComboDisciplina(Curso curso) {
        try {
            DefaultComboBoxModel modelDisciplina = (DefaultComboBoxModel) JComboBoxDisciplina.getModel();
            modelDisciplina.removeAllElements();

            String mensagem = "Preencha com uma disciplina!";
            modelDisciplina.addElement(mensagem);

            List<Disciplina> disciplinas = new DisciplinaController().buscaTodasDisciplinaPorCurso(curso);

            for (Disciplina d : disciplinas) {
                modelDisciplina.addElement(d);
            }

            modelDisciplina.setSelectedItem(mensagem);

        } catch (Exception ex) {
            Logger.getLogger(JPanelTurmas.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void preencherComboProfessores() {
        DefaultComboBoxModel modelProfessores = (DefaultComboBoxModel) JComboBoxProfessor.getModel();
        modelProfessores.removeAllElements();

        String mensagem = "Preencha com um professor!";
        modelProfessores.addElement(mensagem);

        try {
            ArrayList<Professor> professoresBuscados = new ArrayList<>(new ProfessorController().listaProfessor());
            for (Professor p : professoresBuscados) {
                modelProfessores.addElement(p);

            }
        } catch (Exception ex) {
            Logger.getLogger(JPanelDisciplinas.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

        modelProfessores.setSelectedItem(mensagem);
    }

    private void preencherComboDiaSemana() {
        DefaultComboBoxModel modelDiaSemana = (DefaultComboBoxModel) JComboBoxDiaSemana.getModel();
        String mensagem = "Preenche dia semana!";
        modelDiaSemana.addElement(mensagem);
        modelDiaSemana.addElement("Segunda");
        modelDiaSemana.addElement("Terça");
        modelDiaSemana.addElement("Quarta");
        modelDiaSemana.addElement("Quinta");
        modelDiaSemana.addElement("Sexta");
        modelDiaSemana.addElement("Sábado");

        modelDiaSemana.setSelectedItem(mensagem);
    }

    private void preencherComboSalas() {
        try {
            DefaultComboBoxModel modelSalas = (DefaultComboBoxModel) JComboBoxSala.getModel();
            String mensagem = "Preenche dia semana!";
            modelSalas.addElement(mensagem);

            List<Sala> salas = new SalaController().listaSalas();

            for (Sala s : salas) {
                modelSalas.addElement(s);
            }

            modelSalas.setSelectedItem(mensagem);

        } catch (Exception ex) {
            Logger.getLogger(JPanelTurmas.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

}
