/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.alocadorSalas.view;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Mare
 */
public class PaginaInicial extends javax.swing.JFrame {

    /**
     * Creates new form PaginaInicial
     */
    public PaginaInicial() {
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMenu = new javax.swing.JLayeredPane();
        botaoProfessores = new javax.swing.JButton();
        botaoCursos = new javax.swing.JButton();
        botaoDisciplinas = new javax.swing.JButton();
        botaoHorarios = new javax.swing.JButton();
        botaoGrade = new javax.swing.JButton();
        botaoSalas = new javax.swing.JButton();
        botaoInicio = new javax.swing.JButton();
        painelInicial = new javax.swing.JPanel();
        painelCursos = new javax.swing.JPanel();
        painelConfiguracaoCursos = new javax.swing.JPanel();
        lQntDePeriodosCurso = new javax.swing.JLabel();
        lNomeCurso = new javax.swing.JLabel();
        spinnerQntDePeriodos = new javax.swing.JSpinner();
        lSiglaCurso = new javax.swing.JLabel();
        tNomeCurso = new javax.swing.JTextField();
        tSiglaCurso = new javax.swing.JFormattedTextField();
        botaoCadastrarCurso = new javax.swing.JButton();
        botaoAlterarCurso = new javax.swing.JButton();
        botaoExcluirCurso = new javax.swing.JButton();
        botaoBuscarCurso = new javax.swing.JButton();
        painelPesquisaCursos = new javax.swing.JPanel();
        scrollPesquisaCursos = new javax.swing.JScrollPane();
        listaPesquisaCursos = new javax.swing.JList();
        painelProfessores = new javax.swing.JPanel();
        painelConfiguracaoProfessores = new javax.swing.JPanel();
        lNomeProfessores = new javax.swing.JLabel();
        lCursoProfessores = new javax.swing.JLabel();
        tNomeProfessor = new javax.swing.JTextField();
        comboBoxCursoProfessores = new javax.swing.JComboBox();
        botaoBuscarProfessores = new javax.swing.JButton();
        painelPesquisaProfessores = new javax.swing.JPanel();
        scrollPesquisaProfessores = new javax.swing.JScrollPane();
        listaPesquisaProfessores = new javax.swing.JList();
        botaoCadastrarProfessor = new javax.swing.JButton();
        botaoEditarProfessor = new javax.swing.JButton();
        botaoExcluirProfessor = new javax.swing.JButton();
        painelDisciplinas = new javax.swing.JPanel();
        painelConfiguracaoDisciplinas = new javax.swing.JPanel();
        lNomeDisciplina = new javax.swing.JLabel();
        lCursoDisciplina = new javax.swing.JLabel();
        lPeriodoDisciplina = new javax.swing.JLabel();
        lModuloDisciplina = new javax.swing.JLabel();
        tModuloDisciplina = new javax.swing.JFormattedTextField();
        tNomeDisciplina = new javax.swing.JTextField();
        comboBoxCursoDisciplinas = new javax.swing.JComboBox();
        comboBoxPeriodoDisciplinas = new javax.swing.JComboBox();
        painelPesquisaDisciplinas = new javax.swing.JPanel();
        scrolllPesquisaDisciplinas = new javax.swing.JScrollPane();
        listaPesquisaDisciplina = new javax.swing.JList();
        botaoBuscarDisciplina = new javax.swing.JButton();
        botaoCadastrarDisciplina = new javax.swing.JButton();
        botaoEditarDisciplina = new javax.swing.JButton();
        botaoExcluirDisciplina = new javax.swing.JButton();
        painelHorarios = new javax.swing.JPanel();
        painelConfiguracaoHorario = new javax.swing.JPanel();
        lDisciplinaHorario = new javax.swing.JLabel();
        lProfessorHorario = new javax.swing.JLabel();
        comboBoxDisciplinaHorario = new javax.swing.JComboBox();
        comboBoxProfessorHorario = new javax.swing.JComboBox();
        painelCursoHorario = new javax.swing.JPanel();
        lCursoHorario = new javax.swing.JLabel();
        comboBoxCursoHorario = new javax.swing.JComboBox();
        botaoOKCursoHorario = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Menu = new javax.swing.JMenuBar();
        menuAquivo = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        botaoProfessores.setText("Professores");
        botaoProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProfessoresActionPerformed(evt);
            }
        });
        painelMenu.add(botaoProfessores);
        botaoProfessores.setBounds(0, 180, 150, 75);

        botaoCursos.setText("Cursos");
        botaoCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCursosActionPerformed(evt);
            }
        });
        painelMenu.add(botaoCursos);
        botaoCursos.setBounds(0, 90, 150, 75);

        botaoDisciplinas.setText("Matérias");
        botaoDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDisciplinasActionPerformed(evt);
            }
        });
        painelMenu.add(botaoDisciplinas);
        botaoDisciplinas.setBounds(0, 270, 150, 75);

        botaoHorarios.setText("Horários");
        botaoHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHorariosActionPerformed(evt);
            }
        });
        painelMenu.add(botaoHorarios);
        botaoHorarios.setBounds(0, 360, 150, 75);

        botaoGrade.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        botaoGrade.setText("Grade de Matérias");
        botaoGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGradeActionPerformed(evt);
            }
        });
        painelMenu.add(botaoGrade);
        botaoGrade.setBounds(0, 540, 150, 75);

        botaoSalas.setText("Salas");
        botaoSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalasActionPerformed(evt);
            }
        });
        painelMenu.add(botaoSalas);
        botaoSalas.setBounds(0, 450, 150, 75);

        botaoInicio.setText("Início");
        botaoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicioActionPerformed(evt);
            }
        });
        painelMenu.add(botaoInicio);
        botaoInicio.setBounds(0, 0, 150, 75);

        painelInicial.setToolTipText("");

        javax.swing.GroupLayout painelInicialLayout = new javax.swing.GroupLayout(painelInicial);
        painelInicial.setLayout(painelInicialLayout);
        painelInicialLayout.setHorizontalGroup(
            painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        painelInicialLayout.setVerticalGroup(
            painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        painelConfiguracaoCursos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cursos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 102, 102))); // NOI18N

        lQntDePeriodosCurso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lQntDePeriodosCurso.setText("Quantidade de períodos.:");

        lNomeCurso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lNomeCurso.setText("Nome.:");

        spinnerQntDePeriodos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));

        lSiglaCurso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lSiglaCurso.setText("Sigla.:");

        javax.swing.GroupLayout painelConfiguracaoCursosLayout = new javax.swing.GroupLayout(painelConfiguracaoCursos);
        painelConfiguracaoCursos.setLayout(painelConfiguracaoCursosLayout);
        painelConfiguracaoCursosLayout.setHorizontalGroup(
            painelConfiguracaoCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracaoCursosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(painelConfiguracaoCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConfiguracaoCursosLayout.createSequentialGroup()
                        .addComponent(lNomeCurso)
                        .addGap(12, 12, 12)
                        .addComponent(tNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelConfiguracaoCursosLayout.createSequentialGroup()
                        .addComponent(lSiglaCurso)
                        .addGap(18, 18, 18)
                        .addComponent(tSiglaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelConfiguracaoCursosLayout.createSequentialGroup()
                        .addComponent(lQntDePeriodosCurso)
                        .addGap(22, 22, 22)
                        .addComponent(spinnerQntDePeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelConfiguracaoCursosLayout.setVerticalGroup(
            painelConfiguracaoCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracaoCursosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(painelConfiguracaoCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNomeCurso)
                    .addComponent(tNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(painelConfiguracaoCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lSiglaCurso)
                    .addComponent(tSiglaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(painelConfiguracaoCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lQntDePeriodosCurso)
                    .addComponent(spinnerQntDePeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        botaoCadastrarCurso.setText("Cadastrar");
        botaoCadastrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarCursoActionPerformed(evt);
            }
        });

        botaoAlterarCurso.setText("Alterar");
        botaoAlterarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarCursoActionPerformed(evt);
            }
        });

        botaoExcluirCurso.setText("Excluir");
        botaoExcluirCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirCursoActionPerformed(evt);
            }
        });

        botaoBuscarCurso.setText("Buscar");
        botaoBuscarCurso.setPreferredSize(new java.awt.Dimension(100, 50));

        painelPesquisaCursos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Resultado da Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        listaPesquisaCursos.setModel(new DefaultListModel());
        scrollPesquisaCursos.setViewportView(listaPesquisaCursos);

        javax.swing.GroupLayout painelPesquisaCursosLayout = new javax.swing.GroupLayout(painelPesquisaCursos);
        painelPesquisaCursos.setLayout(painelPesquisaCursosLayout);
        painelPesquisaCursosLayout.setHorizontalGroup(
            painelPesquisaCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPesquisaCursos)
                .addContainerGap())
        );
        painelPesquisaCursosLayout.setVerticalGroup(
            painelPesquisaCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPesquisaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelCursosLayout = new javax.swing.GroupLayout(painelCursos);
        painelCursos.setLayout(painelCursosLayout);
        painelCursosLayout.setHorizontalGroup(
            painelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painelPesquisaCursos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoBuscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelConfiguracaoCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelCursosLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(botaoCadastrarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(botaoAlterarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoExcluirCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        painelCursosLayout.setVerticalGroup(
            painelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelConfiguracaoCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(botaoBuscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelPesquisaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExcluirCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAlterarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        painelConfiguracaoProfessores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Professores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 102, 102))); // NOI18N

        lNomeProfessores.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lNomeProfessores.setText("Nome.:");

        lCursoProfessores.setDisplayedMnemonic('C');
        lCursoProfessores.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lCursoProfessores.setText("Curso.:");

        comboBoxCursoProfessores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cursos" }));

        javax.swing.GroupLayout painelConfiguracaoProfessoresLayout = new javax.swing.GroupLayout(painelConfiguracaoProfessores);
        painelConfiguracaoProfessores.setLayout(painelConfiguracaoProfessoresLayout);
        painelConfiguracaoProfessoresLayout.setHorizontalGroup(
            painelConfiguracaoProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracaoProfessoresLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(painelConfiguracaoProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConfiguracaoProfessoresLayout.createSequentialGroup()
                        .addComponent(lCursoProfessores)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxCursoProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelConfiguracaoProfessoresLayout.createSequentialGroup()
                        .addComponent(lNomeProfessores)
                        .addGap(18, 18, 18)
                        .addComponent(tNomeProfessor)))
                .addContainerGap())
        );
        painelConfiguracaoProfessoresLayout.setVerticalGroup(
            painelConfiguracaoProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracaoProfessoresLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(painelConfiguracaoProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomeProfessores)
                    .addComponent(tNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(painelConfiguracaoProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCursoProfessores)
                    .addComponent(comboBoxCursoProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        botaoBuscarProfessores.setLabel("Buscar");
        botaoBuscarProfessores.setPreferredSize(new java.awt.Dimension(100, 50));

        painelPesquisaProfessores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado da Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        listaPesquisaProfessores.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrollPesquisaProfessores.setViewportView(listaPesquisaProfessores);

        javax.swing.GroupLayout painelPesquisaProfessoresLayout = new javax.swing.GroupLayout(painelPesquisaProfessores);
        painelPesquisaProfessores.setLayout(painelPesquisaProfessoresLayout);
        painelPesquisaProfessoresLayout.setHorizontalGroup(
            painelPesquisaProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaProfessoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPesquisaProfessores)
                .addContainerGap())
        );
        painelPesquisaProfessoresLayout.setVerticalGroup(
            painelPesquisaProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaProfessoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPesquisaProfessores, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        botaoCadastrarProfessor.setText("Cadastrar");
        botaoCadastrarProfessor.setPreferredSize(new java.awt.Dimension(100, 50));

        botaoEditarProfessor.setText("Editar");
        botaoEditarProfessor.setPreferredSize(new java.awt.Dimension(100, 50));

        botaoExcluirProfessor.setText("Excluir");
        botaoExcluirProfessor.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout painelProfessoresLayout = new javax.swing.GroupLayout(painelProfessores);
        painelProfessores.setLayout(painelProfessoresLayout);
        painelProfessoresLayout.setHorizontalGroup(
            painelProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProfessoresLayout.createSequentialGroup()
                .addGroup(painelProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelProfessoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelPesquisaProfessores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelConfiguracaoProfessores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelProfessoresLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botaoBuscarProfessores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painelProfessoresLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(botaoCadastrarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)
                        .addComponent(botaoEditarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(botaoExcluirProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addContainerGap())
        );
        painelProfessoresLayout.setVerticalGroup(
            painelProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProfessoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelConfiguracaoProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoBuscarProfessores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelPesquisaProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEditarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExcluirProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        botaoBuscarProfessores.getAccessibleContext().setAccessibleName("");

        painelConfiguracaoDisciplinas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Disciplinas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 102, 102))); // NOI18N

        lNomeDisciplina.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lNomeDisciplina.setText("Nome.:");

        lCursoDisciplina.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lCursoDisciplina.setText("Curso.:");

        lPeriodoDisciplina.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lPeriodoDisciplina.setText("Período.:");

        lModuloDisciplina.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lModuloDisciplina.setText("Módulo.:");

        try {
            tModuloDisciplina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        comboBoxCursoDisciplinas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBoxPeriodoDisciplinas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout painelConfiguracaoDisciplinasLayout = new javax.swing.GroupLayout(painelConfiguracaoDisciplinas);
        painelConfiguracaoDisciplinas.setLayout(painelConfiguracaoDisciplinasLayout);
        painelConfiguracaoDisciplinasLayout.setHorizontalGroup(
            painelConfiguracaoDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracaoDisciplinasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(painelConfiguracaoDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConfiguracaoDisciplinasLayout.createSequentialGroup()
                        .addComponent(lNomeDisciplina)
                        .addGap(18, 18, 18)
                        .addComponent(tNomeDisciplina))
                    .addGroup(painelConfiguracaoDisciplinasLayout.createSequentialGroup()
                        .addGroup(painelConfiguracaoDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelConfiguracaoDisciplinasLayout.createSequentialGroup()
                                .addComponent(lModuloDisciplina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tModuloDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelConfiguracaoDisciplinasLayout.createSequentialGroup()
                                .addComponent(lPeriodoDisciplina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBoxPeriodoDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelConfiguracaoDisciplinasLayout.createSequentialGroup()
                                .addComponent(lCursoDisciplina)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxCursoDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelConfiguracaoDisciplinasLayout.setVerticalGroup(
            painelConfiguracaoDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracaoDisciplinasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConfiguracaoDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomeDisciplina)
                    .addComponent(tNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelConfiguracaoDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCursoDisciplina)
                    .addComponent(comboBoxCursoDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelConfiguracaoDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPeriodoDisciplina)
                    .addComponent(comboBoxPeriodoDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelConfiguracaoDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lModuloDisciplina)
                    .addComponent(tModuloDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        painelPesquisaDisciplinas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado da Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        listaPesquisaDisciplina.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrolllPesquisaDisciplinas.setViewportView(listaPesquisaDisciplina);

        javax.swing.GroupLayout painelPesquisaDisciplinasLayout = new javax.swing.GroupLayout(painelPesquisaDisciplinas);
        painelPesquisaDisciplinas.setLayout(painelPesquisaDisciplinasLayout);
        painelPesquisaDisciplinasLayout.setHorizontalGroup(
            painelPesquisaDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaDisciplinasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrolllPesquisaDisciplinas, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelPesquisaDisciplinasLayout.setVerticalGroup(
            painelPesquisaDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaDisciplinasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrolllPesquisaDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        botaoBuscarDisciplina.setText("Buscar");
        botaoBuscarDisciplina.setPreferredSize(new java.awt.Dimension(100, 50));

        botaoCadastrarDisciplina.setText("Cadastrar");
        botaoCadastrarDisciplina.setPreferredSize(new java.awt.Dimension(100, 50));

        botaoEditarDisciplina.setText("Editar");
        botaoEditarDisciplina.setPreferredSize(new java.awt.Dimension(100, 50));

        botaoExcluirDisciplina.setText("Excluir");
        botaoExcluirDisciplina.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout painelDisciplinasLayout = new javax.swing.GroupLayout(painelDisciplinas);
        painelDisciplinas.setLayout(painelDisciplinasLayout);
        painelDisciplinasLayout.setHorizontalGroup(
            painelDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDisciplinasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelConfiguracaoDisciplinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDisciplinasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoBuscarDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDisciplinasLayout.createSequentialGroup()
                        .addComponent(painelPesquisaDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(painelDisciplinasLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(botaoCadastrarDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoEditarDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(botaoExcluirDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap())
        );
        painelDisciplinasLayout.setVerticalGroup(
            painelDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDisciplinasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelConfiguracaoDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoBuscarDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelPesquisaDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrarDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEditarDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExcluirDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelConfiguracaoHorario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lDisciplinaHorario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lDisciplinaHorario.setText("Disciplina.:");

        lProfessorHorario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lProfessorHorario.setText("Professor.:");

        comboBoxDisciplinaHorario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBoxProfessorHorario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout painelConfiguracaoHorarioLayout = new javax.swing.GroupLayout(painelConfiguracaoHorario);
        painelConfiguracaoHorario.setLayout(painelConfiguracaoHorarioLayout);
        painelConfiguracaoHorarioLayout.setHorizontalGroup(
            painelConfiguracaoHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracaoHorarioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(painelConfiguracaoHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConfiguracaoHorarioLayout.createSequentialGroup()
                        .addComponent(lDisciplinaHorario)
                        .addGap(11, 11, 11)
                        .addComponent(comboBoxDisciplinaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelConfiguracaoHorarioLayout.createSequentialGroup()
                        .addComponent(lProfessorHorario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxProfessorHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelConfiguracaoHorarioLayout.setVerticalGroup(
            painelConfiguracaoHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracaoHorarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConfiguracaoHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDisciplinaHorario)
                    .addComponent(comboBoxDisciplinaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelConfiguracaoHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lProfessorHorario)
                    .addComponent(comboBoxProfessorHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelCursoHorario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Horários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 102, 102))); // NOI18N

        lCursoHorario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lCursoHorario.setText("Curso.:");

        comboBoxCursoHorario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botaoOKCursoHorario.setText("OK");

        javax.swing.GroupLayout painelCursoHorarioLayout = new javax.swing.GroupLayout(painelCursoHorario);
        painelCursoHorario.setLayout(painelCursoHorarioLayout);
        painelCursoHorarioLayout.setHorizontalGroup(
            painelCursoHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCursoHorarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lCursoHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxCursoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(botaoOKCursoHorario)
                .addGap(26, 26, 26))
        );
        painelCursoHorarioLayout.setVerticalGroup(
            painelCursoHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCursoHorarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCursoHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCursoHorario)
                    .addComponent(comboBoxCursoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoOKCursoHorario))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"07-09", null, null, null, null, null, null},
                {"09-11", null, null, null, null, null, null},
                {"11-13", null, null, null, null, null, null},
                {"13-14", null, null, null, null, null, null},
                {"14-16", null, null, null, null, null, null},
                {"16-18", null, null, null, null, null, null},
                {"18-20", null, null, null, null, null, null},
                {"20-22", null, null, null, null, null, null}
            },
            new String [] {
                "Horário", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout painelHorariosLayout = new javax.swing.GroupLayout(painelHorarios);
        painelHorarios.setLayout(painelHorariosLayout);
        painelHorariosLayout.setHorizontalGroup(
            painelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelHorariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelCursoHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelConfiguracaoHorario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        painelHorariosLayout.setVerticalGroup(
            painelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelHorariosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(painelCursoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelConfiguracaoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        menuAquivo.setText("Arquivo");
        Menu.add(menuAquivo);

        menuSobre.setText("Sobre");
        Menu.add(menuSobre);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(painelProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(painelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(painelCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(painelDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(painelHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(822, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCursosActionPerformed
        alteraVisibilidade("botaoCursos");
        alteraCorBotao("botaoCursos");
    }//GEN-LAST:event_botaoCursosActionPerformed

    private void botaoProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProfessoresActionPerformed
        alteraVisibilidade("botaoProfessores");
        alteraCorBotao("botaoProfessores");
    }//GEN-LAST:event_botaoProfessoresActionPerformed

    private void botaoDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDisciplinasActionPerformed
        alteraVisibilidade("botaoDisciplinas");
        alteraCorBotao("botaoDisciplinas");
    }//GEN-LAST:event_botaoDisciplinasActionPerformed

    private void botaoHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHorariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoHorariosActionPerformed

    private void botaoSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSalasActionPerformed

    private void botaoGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoGradeActionPerformed

    private void botaoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicioActionPerformed
        alteraVisibilidade("botaoInicio");
        alteraCorBotao("botaoInicio");
    }//GEN-LAST:event_botaoInicioActionPerformed

    private void botaoCadastrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarCursoActionPerformed
        if (this.tNomeCurso.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Um nome do curso deve ser preenchido");
            return;
        }
        if (this.tSiglaCurso.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Uma sigla do curso deve ser preenchida");
            return;
        }

        DefaultListModel model = (DefaultListModel) listaPesquisaCursos.getModel();
        model.add(model.getSize(), this.tNomeCurso.getText() + "/" + this.tSiglaCurso.getText() + "/" + this.spinnerQntDePeriodos.getValue());

        this.tNomeCurso.setText("");
        this.tSiglaCurso.setText("");
        this.spinnerQntDePeriodos.setValue(1);
    }//GEN-LAST:event_botaoCadastrarCursoActionPerformed

    private void botaoAlterarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarCursoActionPerformed

        if (listaPesquisaCursos.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhum curso selecionado");
            return;
        }

        DefaultListModel model = (DefaultListModel) listaPesquisaCursos.getModel();
        String textoSelecionado = (String) model.getElementAt(listaPesquisaCursos.getSelectedIndex());
        
        this.tNomeCurso.setText(textoSelecionado.split("/")[0]);
        this.tSiglaCurso.setText(textoSelecionado.split("/")[1]);
        this.spinnerQntDePeriodos.setValue(Integer.parseInt(textoSelecionado.split("/")[2]));
    }//GEN-LAST:event_botaoAlterarCursoActionPerformed

    private void botaoExcluirCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirCursoActionPerformed

        if (listaPesquisaCursos.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhum curso selecionado");
            return;
        }

        DefaultListModel model = (DefaultListModel) listaPesquisaCursos.getModel();
        model.remove(listaPesquisaCursos.getSelectedIndex());

        this.tNomeCurso.setText("");
        this.tSiglaCurso.setText("");
        this.spinnerQntDePeriodos.setValue(1);
    }//GEN-LAST:event_botaoExcluirCursoActionPerformed

    private void alteraVisibilidade(String nomeBotao) {
        painelInicial.setVisible(nomeBotao.equalsIgnoreCase("botaoInicio"));
        painelCursos.setVisible(nomeBotao.equalsIgnoreCase("botaoCursos"));
        painelProfessores.setVisible(nomeBotao.equalsIgnoreCase("botaoProfessores"));
        painelDisciplinas.setVisible(nomeBotao.equalsIgnoreCase("botaoDisciplinas"));
        painelHorarios.setVisible(nomeBotao.equalsIgnoreCase("botaoHorarios"));
        //painelSalas.setVisible(nomeBotao.equalsIgnoreCase("botaoSalas"));
        //painelGrade.setVisible(nomeBotao.equalsIgnoreCase("botaoGrade"));
    }

    private void alteraCorBotao(String nomeBotao) {
        botaoCursos.setBackground(nomeBotao.equalsIgnoreCase("botaoCursos") ? Color.ORANGE : new Color(240, 240, 240));
        botaoHorarios.setBackground(nomeBotao.equalsIgnoreCase("botaoHorarios") ? Color.ORANGE : new Color(240, 240, 240));
        botaoSalas.setBackground(nomeBotao.equalsIgnoreCase("botaoSalas") ? Color.ORANGE : new Color(240, 240, 240));
        botaoProfessores.setBackground(nomeBotao.equalsIgnoreCase("botaoProfessores") ? Color.ORANGE : new Color(240, 240, 240));
        botaoDisciplinas.setBackground(nomeBotao.equalsIgnoreCase("botaoDisciplinas") ? Color.ORANGE : new Color(240, 240, 240));
        botaoInicio.setBackground(nomeBotao.equalsIgnoreCase("botaoInicio") ? Color.ORANGE : new Color(240, 240, 240));
        botaoGrade.setBackground(nomeBotao.equalsIgnoreCase("botaoGrade") ? Color.ORANGE : new Color(240, 240, 240));
    }

    /**
     * @param args the command line arguments
     */
    public void run() {
        new PaginaInicial().setVisible(true);

        alteraVisibilidade("botaoInicio");
        alteraCorBotao("botaoInicio");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton botaoAlterarCurso;
    private javax.swing.JButton botaoBuscarCurso;
    private javax.swing.JButton botaoBuscarDisciplina;
    private javax.swing.JButton botaoBuscarProfessores;
    private javax.swing.JButton botaoCadastrarCurso;
    private javax.swing.JButton botaoCadastrarDisciplina;
    private javax.swing.JButton botaoCadastrarProfessor;
    private javax.swing.JButton botaoCursos;
    private javax.swing.JButton botaoDisciplinas;
    private javax.swing.JButton botaoEditarDisciplina;
    private javax.swing.JButton botaoEditarProfessor;
    private javax.swing.JButton botaoExcluirCurso;
    private javax.swing.JButton botaoExcluirDisciplina;
    private javax.swing.JButton botaoExcluirProfessor;
    private javax.swing.JButton botaoGrade;
    private javax.swing.JButton botaoHorarios;
    private javax.swing.JButton botaoInicio;
    private javax.swing.JToggleButton botaoOKCursoHorario;
    private javax.swing.JButton botaoProfessores;
    private javax.swing.JButton botaoSalas;
    private javax.swing.JComboBox comboBoxCursoDisciplinas;
    private javax.swing.JComboBox comboBoxCursoHorario;
    private javax.swing.JComboBox comboBoxCursoProfessores;
    private javax.swing.JComboBox comboBoxDisciplinaHorario;
    private javax.swing.JComboBox comboBoxPeriodoDisciplinas;
    private javax.swing.JComboBox comboBoxProfessorHorario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lCursoDisciplina;
    private javax.swing.JLabel lCursoHorario;
    private javax.swing.JLabel lCursoProfessores;
    private javax.swing.JLabel lDisciplinaHorario;
    private javax.swing.JLabel lModuloDisciplina;
    private javax.swing.JLabel lNomeCurso;
    private javax.swing.JLabel lNomeDisciplina;
    private javax.swing.JLabel lNomeProfessores;
    private javax.swing.JLabel lPeriodoDisciplina;
    private javax.swing.JLabel lProfessorHorario;
    private javax.swing.JLabel lQntDePeriodosCurso;
    private javax.swing.JLabel lSiglaCurso;
    private javax.swing.JList listaPesquisaCursos;
    private javax.swing.JList listaPesquisaDisciplina;
    private javax.swing.JList listaPesquisaProfessores;
    private javax.swing.JMenu menuAquivo;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JPanel painelConfiguracaoCursos;
    private javax.swing.JPanel painelConfiguracaoDisciplinas;
    private javax.swing.JPanel painelConfiguracaoHorario;
    private javax.swing.JPanel painelConfiguracaoProfessores;
    private javax.swing.JPanel painelCursoHorario;
    private javax.swing.JPanel painelCursos;
    private javax.swing.JPanel painelDisciplinas;
    private javax.swing.JPanel painelHorarios;
    private javax.swing.JPanel painelInicial;
    private javax.swing.JLayeredPane painelMenu;
    private javax.swing.JPanel painelPesquisaCursos;
    private javax.swing.JPanel painelPesquisaDisciplinas;
    private javax.swing.JPanel painelPesquisaProfessores;
    private javax.swing.JPanel painelProfessores;
    private javax.swing.JScrollPane scrollPesquisaCursos;
    private javax.swing.JScrollPane scrollPesquisaProfessores;
    private javax.swing.JScrollPane scrolllPesquisaDisciplinas;
    private javax.swing.JSpinner spinnerQntDePeriodos;
    private javax.swing.JFormattedTextField tModuloDisciplina;
    private javax.swing.JTextField tNomeCurso;
    private javax.swing.JTextField tNomeDisciplina;
    private javax.swing.JTextField tNomeProfessor;
    private javax.swing.JFormattedTextField tSiglaCurso;
    // End of variables declaration//GEN-END:variables
}
